# Подключаю образ PostgreSQL
FROM postgres:latest

# Установка параметров окружения postgreSQL
ENV POSTGRES_DB=coworking_db
ENV POSTGRES_USER=root
ENV POSTGRES_PASSWORD=123456

# Старт PostgreSQL
CMD ["postgres"]