server:
  port: 9999

spring:
  # подключение к БД
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5420/coworking_db
    username: root
    password: 123456
  # автоматическое создание и обновление таблиц
  jpa:
    hibernate:
      ddl-auto: update
      show_sql: true
      use_sql_comments: true
      format_sql: true


# управление миграцией схем данных
flyway:
  url: jdbc:postgresql://localhost:5420/coworking_db
  user: root
  password: 123456
  enabled: true
  locations:
    - 'classpath:db/migration'

#
logging:
  level:
    org.springframework: INFO

