version: '3'
services:
  coworking_db:
    image: postgres:latest
    container_name: container_db
    ports:
      - "5420:5432"
    environment:
      POSTGRES_DB: coworking_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    restart: always
    volumes:
      - ./postgreSQL/pg_data:/var/lib/postgres/data
      - ./postgreSQL/database_dump.sql:/docker-entrypoint-initdb.d/database_dump.sql

  spring:
    build:
      dockerfile: Dockerfile
      context: ../build/libs
    ports:
      - "9999:8080"
    depends_on:
      - coworking_db